### ISSUE TITLE
iOS 8 crash Contacts Library not loaded

### ISSUE THREAD

**Issue by isandboy** [nixzhu/Proposer#14]
I have a crash in iOS 8,  beacuse the library use Contacts library, but Contacts library is available  in iOS 9.0

dyld: Library not loaded: /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence
  Referenced from: /System/Library/Frameworks/Contacts.framework/Contacts
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence: mach-o, but not built for iOS simulator

**Comment by nixzhu** [comment]
Drop iOS 8 support. Or drag the Proposer.swift to your project, modify it as you need.

**Comment by isandboy** [comment]
> Drop iOS 8 support. Or drag the Proposer.swift to your project, modify it as you need.

I got it, thanks
