### ISSUE TITLE
Doesn't ask permission for Contacts

### ISSUE THREAD

**Issue by mohsinka** [nixzhu/Proposer#7]
Hi, Thank you for this wonderful library. I however am having some trouble asking for permissions for Contacts. The thing is, when I use this following code, it just assumes that the callback is for the agreed action, and goes into `case: .Authorized` in private method `proposeToAccessContacts` in Proposer.swift. It doesn't even take any interaction from user and goes into authorized. Please help.

`let contacts: PrivateResource = .Contacts`

`proposeToAccess(contacts, agreed:
            {
                self.delegate?.successAction(self)  //Always successful without any user interaction
            },
                        rejected:
            {
                self.delegate?.failureAction(self)
            })`

**Comment by nixzhu** [comment]
It's a normal behavior if you already get the permission to access Contacts.

If you like to test it from scratch, you need to reset your device's settings first. Goto iOS Settings (General > Reset > Reset Location & Privacy). Then run your app again.
