### ISSUE TITLE
Push Notifications?

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [nixzhu/Proposer#8]
Thanks for sharing your work!
I would like to if there is any way to prompt user for allowing push notifications?

**Comment by nixzhu** [comment]
We usually use the third party remote push services, use theirs SDK to prompt user. 

I will add a new case if you need to do it yourself.

**Comment by AnnieNinaJoyceV** [comment]
That will be great! Thank you!

**Comment by nixzhu** [comment]
Version 1.1.0 has been released.
